import React from 'react';
import { Link } from 'react-router';

const pageB = () => {
  return (
    <div>
      <h1>PageB</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe exercitationem, vitae ipsam ex id. Quia natus neque ut voluptatem minima amet quae autem illo officiis nam voluptate, sed, non at, illum error similique culpa tenetur ab cupiditate. Quisquam molestiae veritatis voluptatibus quibusdam quae, molestias totam numquam eligendi esse illum deleniti officiis dolorum iusto, earum consequuntur. Obcaecati inventore animi veritatis veniam asperiores similique, deleniti quia. Velit laboriosam quis hic quod ipsum ut autem omnis repellendus, maxime eveniet amet aperiam dolorem! Illum cumque veniam atque illo qui, impedit cupiditate quisquam, laudantium quasi maxime saepe aliquid facilis quos dolores perspiciatis exercitationem nesciunt in at necessitatibus ab eveniet quibusdam fuga! Tempora culpa itaque expedita, exercitationem beatae omnis consectetur provident vitae molestias, nihil dolorem fugit amet odio ratione asperiores repellendus voluptatum accusantium similique sint deleniti, dignissimos tempore.</p>
      <p> Suscipit, fuga, quisquam! Est porro, laborum, temporibus iure aspernatur recusandae voluptate. Rem doloribus officiis itaque eum consectetur error recusandae cum quidem tempora ratione nostrum praesentium voluptates et voluptatum, aliquid soluta obcaecati dolores eos vel facere adipisci corrupti, excepturi expedita. Consequuntur quod minima tempore autem corporis dicta debitis odit, tenetur dolor facere neque nulla molestias nesciunt beatae, laborum saepe voluptatem et at blanditiis vero recusandae ad accusantium. Omnis nobis at, sequi voluptas odit commodi natus quisquam doloremque tempore doloribus, ut, labore voluptatibus voluptatem ullam molestias expedita? Ipsum est voluptatum deleniti perspiciatis ducimus quia odio reiciendis, alias? Ipsam accusamus, est! Obcaecati expedita enim nam temporibus quibusdam eum ipsa labore! Iste earum distinctio praesentium dolores quas, odit sint ut consectetur, quo iusto quasi exercitationem.</p>
      <p>Animi eos officia porro deleniti qui ut iusto ab minus fugit modi molestias nulla maiores, id aliquid natus, exercitationem. Eos temporibus est unde, inventore voluptatum, hic ad, sunt distinctio, impedit ab nostrum quis id quo. Natus quia pariatur, alias laudantium incidunt assumenda, quos, illum sit voluptas minus quas nihil dolorum soluta. Accusantium, repellendus! Debitis impedit repellendus perferendis, facere dignissimos est facilis harum, iure laudantium tempore, ipsam eaque voluptates alias deleniti, perspiciatis temporibus. Eligendi, sed, porro? Itaque obcaecati id corporis impedit.</p>
      <p>Aperiam nostrum, mollitia at quidem culpa, in fugiat eveniet? Libero debitis excepturi voluptatibus alias cupiditate doloremque dolores architecto recusandae tempore, porro magnam nesciunt laboriosam, tenetur eius ratione sapiente explicabo, atque. Laboriosam, modi provident eaque facere laborum ipsa obcaecati sit, tempore veniam culpa explicabo repellendus unde placeat id soluta, quibusdam beatae, repudiandae molestias. Provident optio dignissimos saepe, eum ipsum hic! Similique molestiae tempora quasi, dolorum at ab totam.</p>
    </div>
  )
}

export default pageB;
